version: '3'
services:
  
  mongodb:
      image: mongo
      volumes:
        - mongodata:/data/db
     
  microservice:
    depends_on:
      - mongodb
    build: .
    image: rachid1234/cloud-native-go:v1
    environment: 
      - PORT=9090
    ports:
      - 8080:9090
    deploy:
      replicas: 10
      restart_policy:
        condition: on-failure

volumes:
  mongodata: {}
