apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: mongo
spec:
  replicas: 1
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
        - mongo
  template:
    metadata: 
      labels:
        app: mongo
    spec:  
      containers:
      - name: mongo
        image: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
          - name: mongodb-data
            mountPath: /data/db 
      volumes:
      - name: mongodb-data
        persistentVolumeClaim: #Referencing the PersistentVolumeClaim by name in the pod volume
          claimName: mongodb-pvc
   