apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongo
spec:
  selector:
    app: mongo
  ports:
  - name: default
    protocol: TCP
    port: 27017
    targetPort: 27017
  #clusterIP: None
  
