version: '3'
services:
  
  mongodb_service:
      image: mongo
      volumes:
        - mongodata:/data/db
      deploy:
        placement:
          constraints: [node.role == manager]
     
  microservice:
    depends_on:
      - mongodb_service
    build: .
    image: rachid123/cloud-native-go:v1
    environment: 
      - PORT=9090
    ports:
      - 8080-8090:9090
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure

volumes:
  mongodata: {}
